name: publish
on:
  push:
    branches:
      - 'master'
    paths:
      - 'version.txt'
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: python3 -m pip install --upgrade build && python3 -m pip install --upgrade twine
      - name: Build
        run: python3 -m build
      - name: Publish
        run: python3 -m twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*